version: '2'

services:
    elk:
        image: sebp/elk:latest
        ports:
          - "9200:9200"
          - "5601:5601"
        volumes:
          - ./volumes/elasticsearch:/var/lib/elasticsearch